sudo: required
services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/node .
  - docker images $DOCKER_USERNAME/node

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/node
  on:
    branch: master

